// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/genomics/v1/reads.proto

package com.google.genomics.v1;

/**
 * Protobuf type {@code google.genomics.v1.CoverageBucket}
 *
 * <pre>
 * A bucket over which read coverage has been precomputed. A bucket corresponds
 * to a specific range of the reference sequence.
 * </pre>
 */
public  final class CoverageBucket extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:google.genomics.v1.CoverageBucket)
    CoverageBucketOrBuilder {
  // Use CoverageBucket.newBuilder() to construct.
  private CoverageBucket(com.google.protobuf.GeneratedMessage.Builder builder) {
    super(builder);
  }
  private CoverageBucket() {
    meanCoverage_ = 0F;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private CoverageBucket(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.genomics.v1.Range.Builder subBuilder = null;
            if (range_ != null) {
              subBuilder = range_.toBuilder();
            }
            range_ = input.readMessage(com.google.genomics.v1.Range.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(range_);
              range_ = subBuilder.buildPartial();
            }

            break;
          }
          case 21: {

            meanCoverage_ = input.readFloat();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.genomics.v1.ReadsProto.internal_static_google_genomics_v1_CoverageBucket_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.genomics.v1.ReadsProto.internal_static_google_genomics_v1_CoverageBucket_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.genomics.v1.CoverageBucket.class, com.google.genomics.v1.CoverageBucket.Builder.class);
  }

  public static final int RANGE_FIELD_NUMBER = 1;
  private com.google.genomics.v1.Range range_;
  /**
   * <code>optional .google.genomics.v1.Range range = 1;</code>
   *
   * <pre>
   * The genomic coordinate range spanned by this bucket.
   * </pre>
   */
  public boolean hasRange() {
    return range_ != null;
  }
  /**
   * <code>optional .google.genomics.v1.Range range = 1;</code>
   *
   * <pre>
   * The genomic coordinate range spanned by this bucket.
   * </pre>
   */
  public com.google.genomics.v1.Range getRange() {
    return range_ == null ? com.google.genomics.v1.Range.getDefaultInstance() : range_;
  }
  /**
   * <code>optional .google.genomics.v1.Range range = 1;</code>
   *
   * <pre>
   * The genomic coordinate range spanned by this bucket.
   * </pre>
   */
  public com.google.genomics.v1.RangeOrBuilder getRangeOrBuilder() {
    return getRange();
  }

  public static final int MEAN_COVERAGE_FIELD_NUMBER = 2;
  private float meanCoverage_;
  /**
   * <code>optional float mean_coverage = 2;</code>
   *
   * <pre>
   * The average number of reads which are aligned to each individual
   * reference base in this bucket.
   * </pre>
   */
  public float getMeanCoverage() {
    return meanCoverage_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (range_ != null) {
      output.writeMessage(1, getRange());
    }
    if (meanCoverage_ != 0F) {
      output.writeFloat(2, meanCoverage_);
    }
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (range_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getRange());
    }
    if (meanCoverage_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, meanCoverage_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static com.google.genomics.v1.CoverageBucket parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.genomics.v1.CoverageBucket parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.genomics.v1.CoverageBucket parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.genomics.v1.CoverageBucket parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.genomics.v1.CoverageBucket parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.google.genomics.v1.CoverageBucket parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.google.genomics.v1.CoverageBucket parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.google.genomics.v1.CoverageBucket parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.google.genomics.v1.CoverageBucket parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.google.genomics.v1.CoverageBucket parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.genomics.v1.CoverageBucket prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code google.genomics.v1.CoverageBucket}
   *
   * <pre>
   * A bucket over which read coverage has been precomputed. A bucket corresponds
   * to a specific range of the reference sequence.
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.genomics.v1.CoverageBucket)
      com.google.genomics.v1.CoverageBucketOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.genomics.v1.ReadsProto.internal_static_google_genomics_v1_CoverageBucket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.genomics.v1.ReadsProto.internal_static_google_genomics_v1_CoverageBucket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.genomics.v1.CoverageBucket.class, com.google.genomics.v1.CoverageBucket.Builder.class);
    }

    // Construct using com.google.genomics.v1.CoverageBucket.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (rangeBuilder_ == null) {
        range_ = null;
      } else {
        range_ = null;
        rangeBuilder_ = null;
      }
      meanCoverage_ = 0F;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.genomics.v1.ReadsProto.internal_static_google_genomics_v1_CoverageBucket_descriptor;
    }

    public com.google.genomics.v1.CoverageBucket getDefaultInstanceForType() {
      return com.google.genomics.v1.CoverageBucket.getDefaultInstance();
    }

    public com.google.genomics.v1.CoverageBucket build() {
      com.google.genomics.v1.CoverageBucket result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.google.genomics.v1.CoverageBucket buildPartial() {
      com.google.genomics.v1.CoverageBucket result = new com.google.genomics.v1.CoverageBucket(this);
      if (rangeBuilder_ == null) {
        result.range_ = range_;
      } else {
        result.range_ = rangeBuilder_.build();
      }
      result.meanCoverage_ = meanCoverage_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.genomics.v1.CoverageBucket) {
        return mergeFrom((com.google.genomics.v1.CoverageBucket)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.genomics.v1.CoverageBucket other) {
      if (other == com.google.genomics.v1.CoverageBucket.getDefaultInstance()) return this;
      if (other.hasRange()) {
        mergeRange(other.getRange());
      }
      if (other.getMeanCoverage() != 0F) {
        setMeanCoverage(other.getMeanCoverage());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.genomics.v1.CoverageBucket parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.genomics.v1.CoverageBucket) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.genomics.v1.Range range_ = null;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.genomics.v1.Range, com.google.genomics.v1.Range.Builder, com.google.genomics.v1.RangeOrBuilder> rangeBuilder_;
    /**
     * <code>optional .google.genomics.v1.Range range = 1;</code>
     *
     * <pre>
     * The genomic coordinate range spanned by this bucket.
     * </pre>
     */
    public boolean hasRange() {
      return rangeBuilder_ != null || range_ != null;
    }
    /**
     * <code>optional .google.genomics.v1.Range range = 1;</code>
     *
     * <pre>
     * The genomic coordinate range spanned by this bucket.
     * </pre>
     */
    public com.google.genomics.v1.Range getRange() {
      if (rangeBuilder_ == null) {
        return range_ == null ? com.google.genomics.v1.Range.getDefaultInstance() : range_;
      } else {
        return rangeBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .google.genomics.v1.Range range = 1;</code>
     *
     * <pre>
     * The genomic coordinate range spanned by this bucket.
     * </pre>
     */
    public Builder setRange(com.google.genomics.v1.Range value) {
      if (rangeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        range_ = value;
        onChanged();
      } else {
        rangeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .google.genomics.v1.Range range = 1;</code>
     *
     * <pre>
     * The genomic coordinate range spanned by this bucket.
     * </pre>
     */
    public Builder setRange(
        com.google.genomics.v1.Range.Builder builderForValue) {
      if (rangeBuilder_ == null) {
        range_ = builderForValue.build();
        onChanged();
      } else {
        rangeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .google.genomics.v1.Range range = 1;</code>
     *
     * <pre>
     * The genomic coordinate range spanned by this bucket.
     * </pre>
     */
    public Builder mergeRange(com.google.genomics.v1.Range value) {
      if (rangeBuilder_ == null) {
        if (range_ != null) {
          range_ =
            com.google.genomics.v1.Range.newBuilder(range_).mergeFrom(value).buildPartial();
        } else {
          range_ = value;
        }
        onChanged();
      } else {
        rangeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .google.genomics.v1.Range range = 1;</code>
     *
     * <pre>
     * The genomic coordinate range spanned by this bucket.
     * </pre>
     */
    public Builder clearRange() {
      if (rangeBuilder_ == null) {
        range_ = null;
        onChanged();
      } else {
        range_ = null;
        rangeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .google.genomics.v1.Range range = 1;</code>
     *
     * <pre>
     * The genomic coordinate range spanned by this bucket.
     * </pre>
     */
    public com.google.genomics.v1.Range.Builder getRangeBuilder() {
      
      onChanged();
      return getRangeFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .google.genomics.v1.Range range = 1;</code>
     *
     * <pre>
     * The genomic coordinate range spanned by this bucket.
     * </pre>
     */
    public com.google.genomics.v1.RangeOrBuilder getRangeOrBuilder() {
      if (rangeBuilder_ != null) {
        return rangeBuilder_.getMessageOrBuilder();
      } else {
        return range_ == null ?
            com.google.genomics.v1.Range.getDefaultInstance() : range_;
      }
    }
    /**
     * <code>optional .google.genomics.v1.Range range = 1;</code>
     *
     * <pre>
     * The genomic coordinate range spanned by this bucket.
     * </pre>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.genomics.v1.Range, com.google.genomics.v1.Range.Builder, com.google.genomics.v1.RangeOrBuilder> 
        getRangeFieldBuilder() {
      if (rangeBuilder_ == null) {
        rangeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.genomics.v1.Range, com.google.genomics.v1.Range.Builder, com.google.genomics.v1.RangeOrBuilder>(
                getRange(),
                getParentForChildren(),
                isClean());
        range_ = null;
      }
      return rangeBuilder_;
    }

    private float meanCoverage_ ;
    /**
     * <code>optional float mean_coverage = 2;</code>
     *
     * <pre>
     * The average number of reads which are aligned to each individual
     * reference base in this bucket.
     * </pre>
     */
    public float getMeanCoverage() {
      return meanCoverage_;
    }
    /**
     * <code>optional float mean_coverage = 2;</code>
     *
     * <pre>
     * The average number of reads which are aligned to each individual
     * reference base in this bucket.
     * </pre>
     */
    public Builder setMeanCoverage(float value) {
      
      meanCoverage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float mean_coverage = 2;</code>
     *
     * <pre>
     * The average number of reads which are aligned to each individual
     * reference base in this bucket.
     * </pre>
     */
    public Builder clearMeanCoverage() {
      
      meanCoverage_ = 0F;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:google.genomics.v1.CoverageBucket)
  }

  // @@protoc_insertion_point(class_scope:google.genomics.v1.CoverageBucket)
  private static final com.google.genomics.v1.CoverageBucket DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.genomics.v1.CoverageBucket();
  }

  public static com.google.genomics.v1.CoverageBucket getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  public static final com.google.protobuf.Parser<CoverageBucket> PARSER =
      new com.google.protobuf.AbstractParser<CoverageBucket>() {
    public CoverageBucket parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new CoverageBucket(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<CoverageBucket> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CoverageBucket> getParserForType() {
    return PARSER;
  }

  public com.google.genomics.v1.CoverageBucket getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

