// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/genomics/v1/variants.proto

package com.google.genomics.v1;

/**
 * Protobuf type {@code google.genomics.v1.CreateVariantRequest}
 */
public  final class CreateVariantRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:google.genomics.v1.CreateVariantRequest)
    CreateVariantRequestOrBuilder {
  // Use CreateVariantRequest.newBuilder() to construct.
  private CreateVariantRequest(com.google.protobuf.GeneratedMessage.Builder builder) {
    super(builder);
  }
  private CreateVariantRequest() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private CreateVariantRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.genomics.v1.Variant.Builder subBuilder = null;
            if (variant_ != null) {
              subBuilder = variant_.toBuilder();
            }
            variant_ = input.readMessage(com.google.genomics.v1.Variant.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(variant_);
              variant_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.genomics.v1.VariantsProto.internal_static_google_genomics_v1_CreateVariantRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.genomics.v1.VariantsProto.internal_static_google_genomics_v1_CreateVariantRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.genomics.v1.CreateVariantRequest.class, com.google.genomics.v1.CreateVariantRequest.Builder.class);
  }

  public static final com.google.protobuf.Parser<CreateVariantRequest> PARSER =
      new com.google.protobuf.AbstractParser<CreateVariantRequest>() {
    public CreateVariantRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateVariantRequest(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<CreateVariantRequest> getParserForType() {
    return PARSER;
  }

  public static final int VARIANT_FIELD_NUMBER = 1;
  private com.google.genomics.v1.Variant variant_;
  /**
   * <code>optional .google.genomics.v1.Variant variant = 1;</code>
   *
   * <pre>
   * The variant to be created.
   * </pre>
   */
  public boolean hasVariant() {
    return variant_ != null;
  }
  /**
   * <code>optional .google.genomics.v1.Variant variant = 1;</code>
   *
   * <pre>
   * The variant to be created.
   * </pre>
   */
  public com.google.genomics.v1.Variant getVariant() {
    return variant_ == null ? com.google.genomics.v1.Variant.getDefaultInstance() : variant_;
  }
  /**
   * <code>optional .google.genomics.v1.Variant variant = 1;</code>
   *
   * <pre>
   * The variant to be created.
   * </pre>
   */
  public com.google.genomics.v1.VariantOrBuilder getVariantOrBuilder() {
    return getVariant();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (variant_ != null) {
      output.writeMessage(1, getVariant());
    }
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (variant_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getVariant());
    }
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static com.google.genomics.v1.CreateVariantRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.genomics.v1.CreateVariantRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.genomics.v1.CreateVariantRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.genomics.v1.CreateVariantRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.genomics.v1.CreateVariantRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.google.genomics.v1.CreateVariantRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.google.genomics.v1.CreateVariantRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.google.genomics.v1.CreateVariantRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.google.genomics.v1.CreateVariantRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.google.genomics.v1.CreateVariantRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return new Builder(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.google.genomics.v1.CreateVariantRequest prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code google.genomics.v1.CreateVariantRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.genomics.v1.CreateVariantRequest)
      com.google.genomics.v1.CreateVariantRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.genomics.v1.VariantsProto.internal_static_google_genomics_v1_CreateVariantRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.genomics.v1.VariantsProto.internal_static_google_genomics_v1_CreateVariantRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.genomics.v1.CreateVariantRequest.class, com.google.genomics.v1.CreateVariantRequest.Builder.class);
    }

    // Construct using com.google.genomics.v1.CreateVariantRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (variantBuilder_ == null) {
        variant_ = null;
      } else {
        variant_ = null;
        variantBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.genomics.v1.VariantsProto.internal_static_google_genomics_v1_CreateVariantRequest_descriptor;
    }

    public com.google.genomics.v1.CreateVariantRequest getDefaultInstanceForType() {
      return com.google.genomics.v1.CreateVariantRequest.getDefaultInstance();
    }

    public com.google.genomics.v1.CreateVariantRequest build() {
      com.google.genomics.v1.CreateVariantRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.google.genomics.v1.CreateVariantRequest buildPartial() {
      com.google.genomics.v1.CreateVariantRequest result = new com.google.genomics.v1.CreateVariantRequest(this);
      if (variantBuilder_ == null) {
        result.variant_ = variant_;
      } else {
        result.variant_ = variantBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.genomics.v1.CreateVariantRequest) {
        return mergeFrom((com.google.genomics.v1.CreateVariantRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.genomics.v1.CreateVariantRequest other) {
      if (other == com.google.genomics.v1.CreateVariantRequest.getDefaultInstance()) return this;
      if (other.hasVariant()) {
        mergeVariant(other.getVariant());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.genomics.v1.CreateVariantRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.genomics.v1.CreateVariantRequest) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.genomics.v1.Variant variant_ = null;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.genomics.v1.Variant, com.google.genomics.v1.Variant.Builder, com.google.genomics.v1.VariantOrBuilder> variantBuilder_;
    /**
     * <code>optional .google.genomics.v1.Variant variant = 1;</code>
     *
     * <pre>
     * The variant to be created.
     * </pre>
     */
    public boolean hasVariant() {
      return variantBuilder_ != null || variant_ != null;
    }
    /**
     * <code>optional .google.genomics.v1.Variant variant = 1;</code>
     *
     * <pre>
     * The variant to be created.
     * </pre>
     */
    public com.google.genomics.v1.Variant getVariant() {
      if (variantBuilder_ == null) {
        return variant_ == null ? com.google.genomics.v1.Variant.getDefaultInstance() : variant_;
      } else {
        return variantBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .google.genomics.v1.Variant variant = 1;</code>
     *
     * <pre>
     * The variant to be created.
     * </pre>
     */
    public Builder setVariant(com.google.genomics.v1.Variant value) {
      if (variantBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        variant_ = value;
        onChanged();
      } else {
        variantBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .google.genomics.v1.Variant variant = 1;</code>
     *
     * <pre>
     * The variant to be created.
     * </pre>
     */
    public Builder setVariant(
        com.google.genomics.v1.Variant.Builder builderForValue) {
      if (variantBuilder_ == null) {
        variant_ = builderForValue.build();
        onChanged();
      } else {
        variantBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .google.genomics.v1.Variant variant = 1;</code>
     *
     * <pre>
     * The variant to be created.
     * </pre>
     */
    public Builder mergeVariant(com.google.genomics.v1.Variant value) {
      if (variantBuilder_ == null) {
        if (variant_ != null) {
          variant_ =
            com.google.genomics.v1.Variant.newBuilder(variant_).mergeFrom(value).buildPartial();
        } else {
          variant_ = value;
        }
        onChanged();
      } else {
        variantBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .google.genomics.v1.Variant variant = 1;</code>
     *
     * <pre>
     * The variant to be created.
     * </pre>
     */
    public Builder clearVariant() {
      if (variantBuilder_ == null) {
        variant_ = null;
        onChanged();
      } else {
        variant_ = null;
        variantBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .google.genomics.v1.Variant variant = 1;</code>
     *
     * <pre>
     * The variant to be created.
     * </pre>
     */
    public com.google.genomics.v1.Variant.Builder getVariantBuilder() {
      
      onChanged();
      return getVariantFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .google.genomics.v1.Variant variant = 1;</code>
     *
     * <pre>
     * The variant to be created.
     * </pre>
     */
    public com.google.genomics.v1.VariantOrBuilder getVariantOrBuilder() {
      if (variantBuilder_ != null) {
        return variantBuilder_.getMessageOrBuilder();
      } else {
        return variant_ == null ?
            com.google.genomics.v1.Variant.getDefaultInstance() : variant_;
      }
    }
    /**
     * <code>optional .google.genomics.v1.Variant variant = 1;</code>
     *
     * <pre>
     * The variant to be created.
     * </pre>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.genomics.v1.Variant, com.google.genomics.v1.Variant.Builder, com.google.genomics.v1.VariantOrBuilder> 
        getVariantFieldBuilder() {
      if (variantBuilder_ == null) {
        variantBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.genomics.v1.Variant, com.google.genomics.v1.Variant.Builder, com.google.genomics.v1.VariantOrBuilder>(
                getVariant(),
                getParentForChildren(),
                isClean());
        variant_ = null;
      }
      return variantBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:google.genomics.v1.CreateVariantRequest)
  }

  // @@protoc_insertion_point(class_scope:google.genomics.v1.CreateVariantRequest)
  private static final com.google.genomics.v1.CreateVariantRequest defaultInstance;static {
    defaultInstance = new com.google.genomics.v1.CreateVariantRequest();
  }

  public static com.google.genomics.v1.CreateVariantRequest getDefaultInstance() {
    return defaultInstance;
  }

  public com.google.genomics.v1.CreateVariantRequest getDefaultInstanceForType() {
    return defaultInstance;
  }

}

