// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/genomics/v1/variants.proto

package com.google.genomics.v1;

public interface DeleteVariantSetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.genomics.v1.DeleteVariantSetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string variant_set_id = 1;</code>
   *
   * <pre>
   * The ID of the variant set to be deleted.
   * </pre>
   */
  java.lang.String getVariantSetId();
  /**
   * <code>optional string variant_set_id = 1;</code>
   *
   * <pre>
   * The ID of the variant set to be deleted.
   * </pre>
   */
  com.google.protobuf.ByteString
      getVariantSetIdBytes();
}
