// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/genomics/v1/datasets.proto

package com.google.genomics.v1;

public interface GetDatasetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.genomics.v1.GetDatasetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string dataset_id = 1;</code>
   *
   * <pre>
   * The ID of the dataset.
   * </pre>
   */
  java.lang.String getDatasetId();
  /**
   * <code>optional string dataset_id = 1;</code>
   *
   * <pre>
   * The ID of the dataset.
   * </pre>
   */
  com.google.protobuf.ByteString
      getDatasetIdBytes();
}
