// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/genomics/v1/variants.proto

package com.google.genomics.v1;

public interface ImportVariantsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.genomics.v1.ImportVariantsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string call_set_ids = 1;</code>
   *
   * <pre>
   * IDs of the call sets that were created.
   * </pre>
   */
  com.google.protobuf.ProtocolStringList
      getCallSetIdsList();
  /**
   * <code>repeated string call_set_ids = 1;</code>
   *
   * <pre>
   * IDs of the call sets that were created.
   * </pre>
   */
  int getCallSetIdsCount();
  /**
   * <code>repeated string call_set_ids = 1;</code>
   *
   * <pre>
   * IDs of the call sets that were created.
   * </pre>
   */
  java.lang.String getCallSetIds(int index);
  /**
   * <code>repeated string call_set_ids = 1;</code>
   *
   * <pre>
   * IDs of the call sets that were created.
   * </pre>
   */
  com.google.protobuf.ByteString
      getCallSetIdsBytes(int index);
}
