// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/genomics/v1/readalignment.proto

package com.google.genomics.v1;

public interface LinearAlignmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.genomics.v1.LinearAlignment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .google.genomics.v1.Position position = 1;</code>
   *
   * <pre>
   * The position of this alignment.
   * </pre>
   */
  boolean hasPosition();
  /**
   * <code>optional .google.genomics.v1.Position position = 1;</code>
   *
   * <pre>
   * The position of this alignment.
   * </pre>
   */
  com.google.genomics.v1.Position getPosition();
  /**
   * <code>optional .google.genomics.v1.Position position = 1;</code>
   *
   * <pre>
   * The position of this alignment.
   * </pre>
   */
  com.google.genomics.v1.PositionOrBuilder getPositionOrBuilder();

  /**
   * <code>optional int32 mapping_quality = 2;</code>
   *
   * <pre>
   * The mapping quality of this alignment. Represents how likely
   * the read maps to this position as opposed to other locations.
   * </pre>
   */
  int getMappingQuality();

  /**
   * <code>repeated .google.genomics.v1.CigarUnit cigar = 3;</code>
   *
   * <pre>
   * Represents the local alignment of this sequence (alignment matches, indels,
   * etc) against the reference.
   * </pre>
   */
  java.util.List<com.google.genomics.v1.CigarUnit> 
      getCigarList();
  /**
   * <code>repeated .google.genomics.v1.CigarUnit cigar = 3;</code>
   *
   * <pre>
   * Represents the local alignment of this sequence (alignment matches, indels,
   * etc) against the reference.
   * </pre>
   */
  com.google.genomics.v1.CigarUnit getCigar(int index);
  /**
   * <code>repeated .google.genomics.v1.CigarUnit cigar = 3;</code>
   *
   * <pre>
   * Represents the local alignment of this sequence (alignment matches, indels,
   * etc) against the reference.
   * </pre>
   */
  int getCigarCount();
  /**
   * <code>repeated .google.genomics.v1.CigarUnit cigar = 3;</code>
   *
   * <pre>
   * Represents the local alignment of this sequence (alignment matches, indels,
   * etc) against the reference.
   * </pre>
   */
  java.util.List<? extends com.google.genomics.v1.CigarUnitOrBuilder> 
      getCigarOrBuilderList();
  /**
   * <code>repeated .google.genomics.v1.CigarUnit cigar = 3;</code>
   *
   * <pre>
   * Represents the local alignment of this sequence (alignment matches, indels,
   * etc) against the reference.
   * </pre>
   */
  com.google.genomics.v1.CigarUnitOrBuilder getCigarOrBuilder(
      int index);
}
