// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/genomics/v1/variants.proto

package com.google.genomics.v1;

/**
 * Protobuf type {@code google.genomics.v1.MergeVariantsRequest}
 */
public  final class MergeVariantsRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:google.genomics.v1.MergeVariantsRequest)
    MergeVariantsRequestOrBuilder {
  // Use MergeVariantsRequest.newBuilder() to construct.
  private MergeVariantsRequest(com.google.protobuf.GeneratedMessage.Builder builder) {
    super(builder);
  }
  private MergeVariantsRequest() {
    variantSetId_ = "";
    variants_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private MergeVariantsRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();

            variantSetId_ = bs;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              variants_ = new java.util.ArrayList<com.google.genomics.v1.Variant>();
              mutable_bitField0_ |= 0x00000002;
            }
            variants_.add(input.readMessage(com.google.genomics.v1.Variant.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        variants_ = java.util.Collections.unmodifiableList(variants_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.genomics.v1.VariantsProto.internal_static_google_genomics_v1_MergeVariantsRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.genomics.v1.VariantsProto.internal_static_google_genomics_v1_MergeVariantsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.genomics.v1.MergeVariantsRequest.class, com.google.genomics.v1.MergeVariantsRequest.Builder.class);
  }

  public static final com.google.protobuf.Parser<MergeVariantsRequest> PARSER =
      new com.google.protobuf.AbstractParser<MergeVariantsRequest>() {
    public MergeVariantsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MergeVariantsRequest(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<MergeVariantsRequest> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int VARIANT_SET_ID_FIELD_NUMBER = 1;
  private java.lang.Object variantSetId_;
  /**
   * <code>optional string variant_set_id = 1;</code>
   *
   * <pre>
   * The destination variant set.
   * </pre>
   */
  public java.lang.String getVariantSetId() {
    java.lang.Object ref = variantSetId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        variantSetId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string variant_set_id = 1;</code>
   *
   * <pre>
   * The destination variant set.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getVariantSetIdBytes() {
    java.lang.Object ref = variantSetId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      variantSetId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VARIANTS_FIELD_NUMBER = 2;
  private java.util.List<com.google.genomics.v1.Variant> variants_;
  /**
   * <code>repeated .google.genomics.v1.Variant variants = 2;</code>
   *
   * <pre>
   * The variants to be merged with existing variants.
   * </pre>
   */
  public java.util.List<com.google.genomics.v1.Variant> getVariantsList() {
    return variants_;
  }
  /**
   * <code>repeated .google.genomics.v1.Variant variants = 2;</code>
   *
   * <pre>
   * The variants to be merged with existing variants.
   * </pre>
   */
  public java.util.List<? extends com.google.genomics.v1.VariantOrBuilder> 
      getVariantsOrBuilderList() {
    return variants_;
  }
  /**
   * <code>repeated .google.genomics.v1.Variant variants = 2;</code>
   *
   * <pre>
   * The variants to be merged with existing variants.
   * </pre>
   */
  public int getVariantsCount() {
    return variants_.size();
  }
  /**
   * <code>repeated .google.genomics.v1.Variant variants = 2;</code>
   *
   * <pre>
   * The variants to be merged with existing variants.
   * </pre>
   */
  public com.google.genomics.v1.Variant getVariants(int index) {
    return variants_.get(index);
  }
  /**
   * <code>repeated .google.genomics.v1.Variant variants = 2;</code>
   *
   * <pre>
   * The variants to be merged with existing variants.
   * </pre>
   */
  public com.google.genomics.v1.VariantOrBuilder getVariantsOrBuilder(
      int index) {
    return variants_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!getVariantSetIdBytes().isEmpty()) {
      output.writeBytes(1, getVariantSetIdBytes());
    }
    for (int i = 0; i < variants_.size(); i++) {
      output.writeMessage(2, variants_.get(i));
    }
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!getVariantSetIdBytes().isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getVariantSetIdBytes());
    }
    for (int i = 0; i < variants_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, variants_.get(i));
    }
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static com.google.genomics.v1.MergeVariantsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.genomics.v1.MergeVariantsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.genomics.v1.MergeVariantsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.genomics.v1.MergeVariantsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.genomics.v1.MergeVariantsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.google.genomics.v1.MergeVariantsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.google.genomics.v1.MergeVariantsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.google.genomics.v1.MergeVariantsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.google.genomics.v1.MergeVariantsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.google.genomics.v1.MergeVariantsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return new Builder(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.google.genomics.v1.MergeVariantsRequest prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code google.genomics.v1.MergeVariantsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.genomics.v1.MergeVariantsRequest)
      com.google.genomics.v1.MergeVariantsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.genomics.v1.VariantsProto.internal_static_google_genomics_v1_MergeVariantsRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.genomics.v1.VariantsProto.internal_static_google_genomics_v1_MergeVariantsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.genomics.v1.MergeVariantsRequest.class, com.google.genomics.v1.MergeVariantsRequest.Builder.class);
    }

    // Construct using com.google.genomics.v1.MergeVariantsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getVariantsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      variantSetId_ = "";

      if (variantsBuilder_ == null) {
        variants_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        variantsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.genomics.v1.VariantsProto.internal_static_google_genomics_v1_MergeVariantsRequest_descriptor;
    }

    public com.google.genomics.v1.MergeVariantsRequest getDefaultInstanceForType() {
      return com.google.genomics.v1.MergeVariantsRequest.getDefaultInstance();
    }

    public com.google.genomics.v1.MergeVariantsRequest build() {
      com.google.genomics.v1.MergeVariantsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.google.genomics.v1.MergeVariantsRequest buildPartial() {
      com.google.genomics.v1.MergeVariantsRequest result = new com.google.genomics.v1.MergeVariantsRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.variantSetId_ = variantSetId_;
      if (variantsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          variants_ = java.util.Collections.unmodifiableList(variants_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.variants_ = variants_;
      } else {
        result.variants_ = variantsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.genomics.v1.MergeVariantsRequest) {
        return mergeFrom((com.google.genomics.v1.MergeVariantsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.genomics.v1.MergeVariantsRequest other) {
      if (other == com.google.genomics.v1.MergeVariantsRequest.getDefaultInstance()) return this;
      if (!other.getVariantSetId().isEmpty()) {
        variantSetId_ = other.variantSetId_;
        onChanged();
      }
      if (variantsBuilder_ == null) {
        if (!other.variants_.isEmpty()) {
          if (variants_.isEmpty()) {
            variants_ = other.variants_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureVariantsIsMutable();
            variants_.addAll(other.variants_);
          }
          onChanged();
        }
      } else {
        if (!other.variants_.isEmpty()) {
          if (variantsBuilder_.isEmpty()) {
            variantsBuilder_.dispose();
            variantsBuilder_ = null;
            variants_ = other.variants_;
            bitField0_ = (bitField0_ & ~0x00000002);
            variantsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getVariantsFieldBuilder() : null;
          } else {
            variantsBuilder_.addAllMessages(other.variants_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.genomics.v1.MergeVariantsRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.genomics.v1.MergeVariantsRequest) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object variantSetId_ = "";
    /**
     * <code>optional string variant_set_id = 1;</code>
     *
     * <pre>
     * The destination variant set.
     * </pre>
     */
    public java.lang.String getVariantSetId() {
      java.lang.Object ref = variantSetId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          variantSetId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string variant_set_id = 1;</code>
     *
     * <pre>
     * The destination variant set.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getVariantSetIdBytes() {
      java.lang.Object ref = variantSetId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        variantSetId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string variant_set_id = 1;</code>
     *
     * <pre>
     * The destination variant set.
     * </pre>
     */
    public Builder setVariantSetId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      variantSetId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string variant_set_id = 1;</code>
     *
     * <pre>
     * The destination variant set.
     * </pre>
     */
    public Builder clearVariantSetId() {
      
      variantSetId_ = getDefaultInstance().getVariantSetId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string variant_set_id = 1;</code>
     *
     * <pre>
     * The destination variant set.
     * </pre>
     */
    public Builder setVariantSetIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      variantSetId_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.google.genomics.v1.Variant> variants_ =
      java.util.Collections.emptyList();
    private void ensureVariantsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        variants_ = new java.util.ArrayList<com.google.genomics.v1.Variant>(variants_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.genomics.v1.Variant, com.google.genomics.v1.Variant.Builder, com.google.genomics.v1.VariantOrBuilder> variantsBuilder_;

    /**
     * <code>repeated .google.genomics.v1.Variant variants = 2;</code>
     *
     * <pre>
     * The variants to be merged with existing variants.
     * </pre>
     */
    public java.util.List<com.google.genomics.v1.Variant> getVariantsList() {
      if (variantsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(variants_);
      } else {
        return variantsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .google.genomics.v1.Variant variants = 2;</code>
     *
     * <pre>
     * The variants to be merged with existing variants.
     * </pre>
     */
    public int getVariantsCount() {
      if (variantsBuilder_ == null) {
        return variants_.size();
      } else {
        return variantsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .google.genomics.v1.Variant variants = 2;</code>
     *
     * <pre>
     * The variants to be merged with existing variants.
     * </pre>
     */
    public com.google.genomics.v1.Variant getVariants(int index) {
      if (variantsBuilder_ == null) {
        return variants_.get(index);
      } else {
        return variantsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .google.genomics.v1.Variant variants = 2;</code>
     *
     * <pre>
     * The variants to be merged with existing variants.
     * </pre>
     */
    public Builder setVariants(
        int index, com.google.genomics.v1.Variant value) {
      if (variantsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVariantsIsMutable();
        variants_.set(index, value);
        onChanged();
      } else {
        variantsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.genomics.v1.Variant variants = 2;</code>
     *
     * <pre>
     * The variants to be merged with existing variants.
     * </pre>
     */
    public Builder setVariants(
        int index, com.google.genomics.v1.Variant.Builder builderForValue) {
      if (variantsBuilder_ == null) {
        ensureVariantsIsMutable();
        variants_.set(index, builderForValue.build());
        onChanged();
      } else {
        variantsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.genomics.v1.Variant variants = 2;</code>
     *
     * <pre>
     * The variants to be merged with existing variants.
     * </pre>
     */
    public Builder addVariants(com.google.genomics.v1.Variant value) {
      if (variantsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVariantsIsMutable();
        variants_.add(value);
        onChanged();
      } else {
        variantsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .google.genomics.v1.Variant variants = 2;</code>
     *
     * <pre>
     * The variants to be merged with existing variants.
     * </pre>
     */
    public Builder addVariants(
        int index, com.google.genomics.v1.Variant value) {
      if (variantsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVariantsIsMutable();
        variants_.add(index, value);
        onChanged();
      } else {
        variantsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.genomics.v1.Variant variants = 2;</code>
     *
     * <pre>
     * The variants to be merged with existing variants.
     * </pre>
     */
    public Builder addVariants(
        com.google.genomics.v1.Variant.Builder builderForValue) {
      if (variantsBuilder_ == null) {
        ensureVariantsIsMutable();
        variants_.add(builderForValue.build());
        onChanged();
      } else {
        variantsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.genomics.v1.Variant variants = 2;</code>
     *
     * <pre>
     * The variants to be merged with existing variants.
     * </pre>
     */
    public Builder addVariants(
        int index, com.google.genomics.v1.Variant.Builder builderForValue) {
      if (variantsBuilder_ == null) {
        ensureVariantsIsMutable();
        variants_.add(index, builderForValue.build());
        onChanged();
      } else {
        variantsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.genomics.v1.Variant variants = 2;</code>
     *
     * <pre>
     * The variants to be merged with existing variants.
     * </pre>
     */
    public Builder addAllVariants(
        java.lang.Iterable<? extends com.google.genomics.v1.Variant> values) {
      if (variantsBuilder_ == null) {
        ensureVariantsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, variants_);
        onChanged();
      } else {
        variantsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .google.genomics.v1.Variant variants = 2;</code>
     *
     * <pre>
     * The variants to be merged with existing variants.
     * </pre>
     */
    public Builder clearVariants() {
      if (variantsBuilder_ == null) {
        variants_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        variantsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .google.genomics.v1.Variant variants = 2;</code>
     *
     * <pre>
     * The variants to be merged with existing variants.
     * </pre>
     */
    public Builder removeVariants(int index) {
      if (variantsBuilder_ == null) {
        ensureVariantsIsMutable();
        variants_.remove(index);
        onChanged();
      } else {
        variantsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .google.genomics.v1.Variant variants = 2;</code>
     *
     * <pre>
     * The variants to be merged with existing variants.
     * </pre>
     */
    public com.google.genomics.v1.Variant.Builder getVariantsBuilder(
        int index) {
      return getVariantsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .google.genomics.v1.Variant variants = 2;</code>
     *
     * <pre>
     * The variants to be merged with existing variants.
     * </pre>
     */
    public com.google.genomics.v1.VariantOrBuilder getVariantsOrBuilder(
        int index) {
      if (variantsBuilder_ == null) {
        return variants_.get(index);  } else {
        return variantsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .google.genomics.v1.Variant variants = 2;</code>
     *
     * <pre>
     * The variants to be merged with existing variants.
     * </pre>
     */
    public java.util.List<? extends com.google.genomics.v1.VariantOrBuilder> 
         getVariantsOrBuilderList() {
      if (variantsBuilder_ != null) {
        return variantsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(variants_);
      }
    }
    /**
     * <code>repeated .google.genomics.v1.Variant variants = 2;</code>
     *
     * <pre>
     * The variants to be merged with existing variants.
     * </pre>
     */
    public com.google.genomics.v1.Variant.Builder addVariantsBuilder() {
      return getVariantsFieldBuilder().addBuilder(
          com.google.genomics.v1.Variant.getDefaultInstance());
    }
    /**
     * <code>repeated .google.genomics.v1.Variant variants = 2;</code>
     *
     * <pre>
     * The variants to be merged with existing variants.
     * </pre>
     */
    public com.google.genomics.v1.Variant.Builder addVariantsBuilder(
        int index) {
      return getVariantsFieldBuilder().addBuilder(
          index, com.google.genomics.v1.Variant.getDefaultInstance());
    }
    /**
     * <code>repeated .google.genomics.v1.Variant variants = 2;</code>
     *
     * <pre>
     * The variants to be merged with existing variants.
     * </pre>
     */
    public java.util.List<com.google.genomics.v1.Variant.Builder> 
         getVariantsBuilderList() {
      return getVariantsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.genomics.v1.Variant, com.google.genomics.v1.Variant.Builder, com.google.genomics.v1.VariantOrBuilder> 
        getVariantsFieldBuilder() {
      if (variantsBuilder_ == null) {
        variantsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.google.genomics.v1.Variant, com.google.genomics.v1.Variant.Builder, com.google.genomics.v1.VariantOrBuilder>(
                variants_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        variants_ = null;
      }
      return variantsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:google.genomics.v1.MergeVariantsRequest)
  }

  // @@protoc_insertion_point(class_scope:google.genomics.v1.MergeVariantsRequest)
  private static final com.google.genomics.v1.MergeVariantsRequest defaultInstance;static {
    defaultInstance = new com.google.genomics.v1.MergeVariantsRequest();
  }

  public static com.google.genomics.v1.MergeVariantsRequest getDefaultInstance() {
    return defaultInstance;
  }

  public com.google.genomics.v1.MergeVariantsRequest getDefaultInstanceForType() {
    return defaultInstance;
  }

}

