// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/genomics/v1/position.proto

package com.google.genomics.v1;

public interface PositionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.genomics.v1.Position)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string reference_name = 1;</code>
   *
   * <pre>
   * The name of the reference in whatever reference set is being used.
   * </pre>
   */
  java.lang.String getReferenceName();
  /**
   * <code>optional string reference_name = 1;</code>
   *
   * <pre>
   * The name of the reference in whatever reference set is being used.
   * </pre>
   */
  com.google.protobuf.ByteString
      getReferenceNameBytes();

  /**
   * <code>optional int64 position = 2;</code>
   *
   * <pre>
   * The 0-based offset from the start of the forward strand for that reference.
   * </pre>
   */
  long getPosition();

  /**
   * <code>optional bool reverse_strand = 3;</code>
   *
   * <pre>
   * Whether this position is on the reverse strand, as opposed to the forward
   * strand.
   * </pre>
   */
  boolean getReverseStrand();
}
