// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/genomics/v1/readgroupset.proto

package com.google.genomics.v1;

public interface ReadGroupSetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.genomics.v1.ReadGroupSet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string id = 1;</code>
   *
   * <pre>
   * The read group set ID.
   * </pre>
   */
  java.lang.String getId();
  /**
   * <code>optional string id = 1;</code>
   *
   * <pre>
   * The read group set ID.
   * </pre>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>optional string dataset_id = 2;</code>
   *
   * <pre>
   * The dataset ID.
   * </pre>
   */
  java.lang.String getDatasetId();
  /**
   * <code>optional string dataset_id = 2;</code>
   *
   * <pre>
   * The dataset ID.
   * </pre>
   */
  com.google.protobuf.ByteString
      getDatasetIdBytes();

  /**
   * <code>optional string reference_set_id = 3;</code>
   *
   * <pre>
   * The reference set the reads in this read group set are aligned to.
   * </pre>
   */
  java.lang.String getReferenceSetId();
  /**
   * <code>optional string reference_set_id = 3;</code>
   *
   * <pre>
   * The reference set the reads in this read group set are aligned to.
   * </pre>
   */
  com.google.protobuf.ByteString
      getReferenceSetIdBytes();

  /**
   * <code>optional string name = 4;</code>
   *
   * <pre>
   * The read group set name. By default this will be initialized to the sample
   * name of the sequenced data contained in this set.
   * </pre>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 4;</code>
   *
   * <pre>
   * The read group set name. By default this will be initialized to the sample
   * name of the sequenced data contained in this set.
   * </pre>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string filename = 5;</code>
   *
   * <pre>
   * The filename of the original source file for this read group set, if any.
   * </pre>
   */
  java.lang.String getFilename();
  /**
   * <code>optional string filename = 5;</code>
   *
   * <pre>
   * The filename of the original source file for this read group set, if any.
   * </pre>
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <code>repeated .google.genomics.v1.ReadGroup read_groups = 6;</code>
   *
   * <pre>
   * The read groups in this set. There are typically 1-10 read groups in a read
   * group set.
   * </pre>
   */
  java.util.List<com.google.genomics.v1.ReadGroup> 
      getReadGroupsList();
  /**
   * <code>repeated .google.genomics.v1.ReadGroup read_groups = 6;</code>
   *
   * <pre>
   * The read groups in this set. There are typically 1-10 read groups in a read
   * group set.
   * </pre>
   */
  com.google.genomics.v1.ReadGroup getReadGroups(int index);
  /**
   * <code>repeated .google.genomics.v1.ReadGroup read_groups = 6;</code>
   *
   * <pre>
   * The read groups in this set. There are typically 1-10 read groups in a read
   * group set.
   * </pre>
   */
  int getReadGroupsCount();
  /**
   * <code>repeated .google.genomics.v1.ReadGroup read_groups = 6;</code>
   *
   * <pre>
   * The read groups in this set. There are typically 1-10 read groups in a read
   * group set.
   * </pre>
   */
  java.util.List<? extends com.google.genomics.v1.ReadGroupOrBuilder> 
      getReadGroupsOrBuilderList();
  /**
   * <code>repeated .google.genomics.v1.ReadGroup read_groups = 6;</code>
   *
   * <pre>
   * The read groups in this set. There are typically 1-10 read groups in a read
   * group set.
   * </pre>
   */
  com.google.genomics.v1.ReadGroupOrBuilder getReadGroupsOrBuilder(
      int index);

  /**
   * <code>map&lt;string, .google.protobuf.ListValue&gt; info = 7;</code>
   *
   * <pre>
   * A map of additional read group set information.
   * </pre>
   */
  java.util.Map<java.lang.String, com.google.protobuf.ListValue>
  getInfo();
}
