// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/genomics/v1/variants.proto

package com.google.genomics.v1;

/**
 * Protobuf type {@code google.genomics.v1.SearchVariantsRequest}
 *
 * <pre>
 * The variant search request.
 * </pre>
 */
public  final class SearchVariantsRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:google.genomics.v1.SearchVariantsRequest)
    SearchVariantsRequestOrBuilder {
  // Use SearchVariantsRequest.newBuilder() to construct.
  private SearchVariantsRequest(com.google.protobuf.GeneratedMessage.Builder builder) {
    super(builder);
  }
  private SearchVariantsRequest() {
    variantSetIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    variantName_ = "";
    callSetIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    referenceName_ = "";
    start_ = 0L;
    end_ = 0L;
    pageToken_ = "";
    pageSize_ = 0;
    maxCalls_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private SearchVariantsRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              variantSetIds_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            variantSetIds_.add(bs);
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();

            variantName_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              callSetIds_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000004;
            }
            callSetIds_.add(bs);
            break;
          }
          case 34: {
            com.google.protobuf.ByteString bs = input.readBytes();

            referenceName_ = bs;
            break;
          }
          case 40: {

            start_ = input.readInt64();
            break;
          }
          case 48: {

            end_ = input.readInt64();
            break;
          }
          case 58: {
            com.google.protobuf.ByteString bs = input.readBytes();

            pageToken_ = bs;
            break;
          }
          case 64: {

            pageSize_ = input.readInt32();
            break;
          }
          case 72: {

            maxCalls_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        variantSetIds_ = variantSetIds_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        callSetIds_ = callSetIds_.getUnmodifiableView();
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.genomics.v1.VariantsProto.internal_static_google_genomics_v1_SearchVariantsRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.genomics.v1.VariantsProto.internal_static_google_genomics_v1_SearchVariantsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.genomics.v1.SearchVariantsRequest.class, com.google.genomics.v1.SearchVariantsRequest.Builder.class);
  }

  private int bitField0_;
  public static final int VARIANT_SET_IDS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList variantSetIds_;
  /**
   * <code>repeated string variant_set_ids = 1;</code>
   *
   * <pre>
   * At most one variant set ID must be provided. Only variants from this
   * variant set will be returned. If omitted, a call set id must be included in
   * the request.
   * </pre>
   */
  public com.google.protobuf.ProtocolStringList
      getVariantSetIdsList() {
    return variantSetIds_;
  }
  /**
   * <code>repeated string variant_set_ids = 1;</code>
   *
   * <pre>
   * At most one variant set ID must be provided. Only variants from this
   * variant set will be returned. If omitted, a call set id must be included in
   * the request.
   * </pre>
   */
  public int getVariantSetIdsCount() {
    return variantSetIds_.size();
  }
  /**
   * <code>repeated string variant_set_ids = 1;</code>
   *
   * <pre>
   * At most one variant set ID must be provided. Only variants from this
   * variant set will be returned. If omitted, a call set id must be included in
   * the request.
   * </pre>
   */
  public java.lang.String getVariantSetIds(int index) {
    return variantSetIds_.get(index);
  }
  /**
   * <code>repeated string variant_set_ids = 1;</code>
   *
   * <pre>
   * At most one variant set ID must be provided. Only variants from this
   * variant set will be returned. If omitted, a call set id must be included in
   * the request.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getVariantSetIdsBytes(int index) {
    return variantSetIds_.getByteString(index);
  }

  public static final int VARIANT_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object variantName_;
  /**
   * <code>optional string variant_name = 2;</code>
   *
   * <pre>
   * Only return variants which have exactly this name.
   * </pre>
   */
  public java.lang.String getVariantName() {
    java.lang.Object ref = variantName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        variantName_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string variant_name = 2;</code>
   *
   * <pre>
   * Only return variants which have exactly this name.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getVariantNameBytes() {
    java.lang.Object ref = variantName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      variantName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CALL_SET_IDS_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList callSetIds_;
  /**
   * <code>repeated string call_set_ids = 3;</code>
   *
   * <pre>
   * Only return variant calls which belong to call sets with these ids.
   * Leaving this blank returns all variant calls. If a variant has no
   * calls belonging to any of these call sets, it won't be returned at all.
   * Currently, variants with no calls from any call set will never be returned.
   * </pre>
   */
  public com.google.protobuf.ProtocolStringList
      getCallSetIdsList() {
    return callSetIds_;
  }
  /**
   * <code>repeated string call_set_ids = 3;</code>
   *
   * <pre>
   * Only return variant calls which belong to call sets with these ids.
   * Leaving this blank returns all variant calls. If a variant has no
   * calls belonging to any of these call sets, it won't be returned at all.
   * Currently, variants with no calls from any call set will never be returned.
   * </pre>
   */
  public int getCallSetIdsCount() {
    return callSetIds_.size();
  }
  /**
   * <code>repeated string call_set_ids = 3;</code>
   *
   * <pre>
   * Only return variant calls which belong to call sets with these ids.
   * Leaving this blank returns all variant calls. If a variant has no
   * calls belonging to any of these call sets, it won't be returned at all.
   * Currently, variants with no calls from any call set will never be returned.
   * </pre>
   */
  public java.lang.String getCallSetIds(int index) {
    return callSetIds_.get(index);
  }
  /**
   * <code>repeated string call_set_ids = 3;</code>
   *
   * <pre>
   * Only return variant calls which belong to call sets with these ids.
   * Leaving this blank returns all variant calls. If a variant has no
   * calls belonging to any of these call sets, it won't be returned at all.
   * Currently, variants with no calls from any call set will never be returned.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getCallSetIdsBytes(int index) {
    return callSetIds_.getByteString(index);
  }

  public static final int REFERENCE_NAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object referenceName_;
  /**
   * <code>optional string reference_name = 4;</code>
   *
   * <pre>
   * Required. Only return variants in this reference sequence.
   * </pre>
   */
  public java.lang.String getReferenceName() {
    java.lang.Object ref = referenceName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        referenceName_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string reference_name = 4;</code>
   *
   * <pre>
   * Required. Only return variants in this reference sequence.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getReferenceNameBytes() {
    java.lang.Object ref = referenceName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      referenceName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int START_FIELD_NUMBER = 5;
  private long start_;
  /**
   * <code>optional int64 start = 5;</code>
   *
   * <pre>
   * The beginning of the window (0-based, inclusive) for which
   * overlapping variants should be returned. If unspecified, defaults to 0.
   * </pre>
   */
  public long getStart() {
    return start_;
  }

  public static final int END_FIELD_NUMBER = 6;
  private long end_;
  /**
   * <code>optional int64 end = 6;</code>
   *
   * <pre>
   * The end of the window, 0-based exclusive. If unspecified or 0, defaults to
   * the length of the reference.
   * </pre>
   */
  public long getEnd() {
    return end_;
  }

  public static final int PAGE_TOKEN_FIELD_NUMBER = 7;
  private volatile java.lang.Object pageToken_;
  /**
   * <code>optional string page_token = 7;</code>
   *
   * <pre>
   * The continuation token, which is used to page through large result sets.
   * To get the next page of results, set this parameter to the value of
   * `nextPageToken` from the previous response.
   * </pre>
   */
  public java.lang.String getPageToken() {
    java.lang.Object ref = pageToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        pageToken_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string page_token = 7;</code>
   *
   * <pre>
   * The continuation token, which is used to page through large result sets.
   * To get the next page of results, set this parameter to the value of
   * `nextPageToken` from the previous response.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getPageTokenBytes() {
    java.lang.Object ref = pageToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pageToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAGE_SIZE_FIELD_NUMBER = 8;
  private int pageSize_;
  /**
   * <code>optional int32 page_size = 8;</code>
   *
   * <pre>
   * The maximum number of variants to return. If unspecified, defaults to 5000.
   * </pre>
   */
  public int getPageSize() {
    return pageSize_;
  }

  public static final int MAX_CALLS_FIELD_NUMBER = 9;
  private int maxCalls_;
  /**
   * <code>optional int32 max_calls = 9;</code>
   *
   * <pre>
   * The maximum number of calls to return. However, at least one variant will
   * always be returned, even if it has more calls than this limit. If
   * unspecified, defaults to 5000.
   * </pre>
   */
  public int getMaxCalls() {
    return maxCalls_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < variantSetIds_.size(); i++) {
      output.writeBytes(1, variantSetIds_.getByteString(i));
    }
    if (!getVariantNameBytes().isEmpty()) {
      output.writeBytes(2, getVariantNameBytes());
    }
    for (int i = 0; i < callSetIds_.size(); i++) {
      output.writeBytes(3, callSetIds_.getByteString(i));
    }
    if (!getReferenceNameBytes().isEmpty()) {
      output.writeBytes(4, getReferenceNameBytes());
    }
    if (start_ != 0L) {
      output.writeInt64(5, start_);
    }
    if (end_ != 0L) {
      output.writeInt64(6, end_);
    }
    if (!getPageTokenBytes().isEmpty()) {
      output.writeBytes(7, getPageTokenBytes());
    }
    if (pageSize_ != 0) {
      output.writeInt32(8, pageSize_);
    }
    if (maxCalls_ != 0) {
      output.writeInt32(9, maxCalls_);
    }
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < variantSetIds_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(variantSetIds_.getByteString(i));
      }
      size += dataSize;
      size += 1 * getVariantSetIdsList().size();
    }
    if (!getVariantNameBytes().isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getVariantNameBytes());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < callSetIds_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(callSetIds_.getByteString(i));
      }
      size += dataSize;
      size += 1 * getCallSetIdsList().size();
    }
    if (!getReferenceNameBytes().isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, getReferenceNameBytes());
    }
    if (start_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, start_);
    }
    if (end_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, end_);
    }
    if (!getPageTokenBytes().isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(7, getPageTokenBytes());
    }
    if (pageSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, pageSize_);
    }
    if (maxCalls_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, maxCalls_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static com.google.genomics.v1.SearchVariantsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.genomics.v1.SearchVariantsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.genomics.v1.SearchVariantsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.genomics.v1.SearchVariantsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.genomics.v1.SearchVariantsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.google.genomics.v1.SearchVariantsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.google.genomics.v1.SearchVariantsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.google.genomics.v1.SearchVariantsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.google.genomics.v1.SearchVariantsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.google.genomics.v1.SearchVariantsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.genomics.v1.SearchVariantsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code google.genomics.v1.SearchVariantsRequest}
   *
   * <pre>
   * The variant search request.
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.genomics.v1.SearchVariantsRequest)
      com.google.genomics.v1.SearchVariantsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.genomics.v1.VariantsProto.internal_static_google_genomics_v1_SearchVariantsRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.genomics.v1.VariantsProto.internal_static_google_genomics_v1_SearchVariantsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.genomics.v1.SearchVariantsRequest.class, com.google.genomics.v1.SearchVariantsRequest.Builder.class);
    }

    // Construct using com.google.genomics.v1.SearchVariantsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      variantSetIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      variantName_ = "";

      callSetIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      referenceName_ = "";

      start_ = 0L;

      end_ = 0L;

      pageToken_ = "";

      pageSize_ = 0;

      maxCalls_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.genomics.v1.VariantsProto.internal_static_google_genomics_v1_SearchVariantsRequest_descriptor;
    }

    public com.google.genomics.v1.SearchVariantsRequest getDefaultInstanceForType() {
      return com.google.genomics.v1.SearchVariantsRequest.getDefaultInstance();
    }

    public com.google.genomics.v1.SearchVariantsRequest build() {
      com.google.genomics.v1.SearchVariantsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.google.genomics.v1.SearchVariantsRequest buildPartial() {
      com.google.genomics.v1.SearchVariantsRequest result = new com.google.genomics.v1.SearchVariantsRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        variantSetIds_ = variantSetIds_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.variantSetIds_ = variantSetIds_;
      result.variantName_ = variantName_;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        callSetIds_ = callSetIds_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.callSetIds_ = callSetIds_;
      result.referenceName_ = referenceName_;
      result.start_ = start_;
      result.end_ = end_;
      result.pageToken_ = pageToken_;
      result.pageSize_ = pageSize_;
      result.maxCalls_ = maxCalls_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.genomics.v1.SearchVariantsRequest) {
        return mergeFrom((com.google.genomics.v1.SearchVariantsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.genomics.v1.SearchVariantsRequest other) {
      if (other == com.google.genomics.v1.SearchVariantsRequest.getDefaultInstance()) return this;
      if (!other.variantSetIds_.isEmpty()) {
        if (variantSetIds_.isEmpty()) {
          variantSetIds_ = other.variantSetIds_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureVariantSetIdsIsMutable();
          variantSetIds_.addAll(other.variantSetIds_);
        }
        onChanged();
      }
      if (!other.getVariantName().isEmpty()) {
        variantName_ = other.variantName_;
        onChanged();
      }
      if (!other.callSetIds_.isEmpty()) {
        if (callSetIds_.isEmpty()) {
          callSetIds_ = other.callSetIds_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureCallSetIdsIsMutable();
          callSetIds_.addAll(other.callSetIds_);
        }
        onChanged();
      }
      if (!other.getReferenceName().isEmpty()) {
        referenceName_ = other.referenceName_;
        onChanged();
      }
      if (other.getStart() != 0L) {
        setStart(other.getStart());
      }
      if (other.getEnd() != 0L) {
        setEnd(other.getEnd());
      }
      if (!other.getPageToken().isEmpty()) {
        pageToken_ = other.pageToken_;
        onChanged();
      }
      if (other.getPageSize() != 0) {
        setPageSize(other.getPageSize());
      }
      if (other.getMaxCalls() != 0) {
        setMaxCalls(other.getMaxCalls());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.genomics.v1.SearchVariantsRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.genomics.v1.SearchVariantsRequest) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList variantSetIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureVariantSetIdsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        variantSetIds_ = new com.google.protobuf.LazyStringArrayList(variantSetIds_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string variant_set_ids = 1;</code>
     *
     * <pre>
     * At most one variant set ID must be provided. Only variants from this
     * variant set will be returned. If omitted, a call set id must be included in
     * the request.
     * </pre>
     */
    public com.google.protobuf.ProtocolStringList
        getVariantSetIdsList() {
      return variantSetIds_.getUnmodifiableView();
    }
    /**
     * <code>repeated string variant_set_ids = 1;</code>
     *
     * <pre>
     * At most one variant set ID must be provided. Only variants from this
     * variant set will be returned. If omitted, a call set id must be included in
     * the request.
     * </pre>
     */
    public int getVariantSetIdsCount() {
      return variantSetIds_.size();
    }
    /**
     * <code>repeated string variant_set_ids = 1;</code>
     *
     * <pre>
     * At most one variant set ID must be provided. Only variants from this
     * variant set will be returned. If omitted, a call set id must be included in
     * the request.
     * </pre>
     */
    public java.lang.String getVariantSetIds(int index) {
      return variantSetIds_.get(index);
    }
    /**
     * <code>repeated string variant_set_ids = 1;</code>
     *
     * <pre>
     * At most one variant set ID must be provided. Only variants from this
     * variant set will be returned. If omitted, a call set id must be included in
     * the request.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getVariantSetIdsBytes(int index) {
      return variantSetIds_.getByteString(index);
    }
    /**
     * <code>repeated string variant_set_ids = 1;</code>
     *
     * <pre>
     * At most one variant set ID must be provided. Only variants from this
     * variant set will be returned. If omitted, a call set id must be included in
     * the request.
     * </pre>
     */
    public Builder setVariantSetIds(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureVariantSetIdsIsMutable();
      variantSetIds_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string variant_set_ids = 1;</code>
     *
     * <pre>
     * At most one variant set ID must be provided. Only variants from this
     * variant set will be returned. If omitted, a call set id must be included in
     * the request.
     * </pre>
     */
    public Builder addVariantSetIds(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureVariantSetIdsIsMutable();
      variantSetIds_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string variant_set_ids = 1;</code>
     *
     * <pre>
     * At most one variant set ID must be provided. Only variants from this
     * variant set will be returned. If omitted, a call set id must be included in
     * the request.
     * </pre>
     */
    public Builder addAllVariantSetIds(
        java.lang.Iterable<java.lang.String> values) {
      ensureVariantSetIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, variantSetIds_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string variant_set_ids = 1;</code>
     *
     * <pre>
     * At most one variant set ID must be provided. Only variants from this
     * variant set will be returned. If omitted, a call set id must be included in
     * the request.
     * </pre>
     */
    public Builder clearVariantSetIds() {
      variantSetIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string variant_set_ids = 1;</code>
     *
     * <pre>
     * At most one variant set ID must be provided. Only variants from this
     * variant set will be returned. If omitted, a call set id must be included in
     * the request.
     * </pre>
     */
    public Builder addVariantSetIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureVariantSetIdsIsMutable();
      variantSetIds_.add(value);
      onChanged();
      return this;
    }

    private java.lang.Object variantName_ = "";
    /**
     * <code>optional string variant_name = 2;</code>
     *
     * <pre>
     * Only return variants which have exactly this name.
     * </pre>
     */
    public java.lang.String getVariantName() {
      java.lang.Object ref = variantName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          variantName_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string variant_name = 2;</code>
     *
     * <pre>
     * Only return variants which have exactly this name.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getVariantNameBytes() {
      java.lang.Object ref = variantName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        variantName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string variant_name = 2;</code>
     *
     * <pre>
     * Only return variants which have exactly this name.
     * </pre>
     */
    public Builder setVariantName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      variantName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string variant_name = 2;</code>
     *
     * <pre>
     * Only return variants which have exactly this name.
     * </pre>
     */
    public Builder clearVariantName() {
      
      variantName_ = getDefaultInstance().getVariantName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string variant_name = 2;</code>
     *
     * <pre>
     * Only return variants which have exactly this name.
     * </pre>
     */
    public Builder setVariantNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      variantName_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList callSetIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureCallSetIdsIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        callSetIds_ = new com.google.protobuf.LazyStringArrayList(callSetIds_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated string call_set_ids = 3;</code>
     *
     * <pre>
     * Only return variant calls which belong to call sets with these ids.
     * Leaving this blank returns all variant calls. If a variant has no
     * calls belonging to any of these call sets, it won't be returned at all.
     * Currently, variants with no calls from any call set will never be returned.
     * </pre>
     */
    public com.google.protobuf.ProtocolStringList
        getCallSetIdsList() {
      return callSetIds_.getUnmodifiableView();
    }
    /**
     * <code>repeated string call_set_ids = 3;</code>
     *
     * <pre>
     * Only return variant calls which belong to call sets with these ids.
     * Leaving this blank returns all variant calls. If a variant has no
     * calls belonging to any of these call sets, it won't be returned at all.
     * Currently, variants with no calls from any call set will never be returned.
     * </pre>
     */
    public int getCallSetIdsCount() {
      return callSetIds_.size();
    }
    /**
     * <code>repeated string call_set_ids = 3;</code>
     *
     * <pre>
     * Only return variant calls which belong to call sets with these ids.
     * Leaving this blank returns all variant calls. If a variant has no
     * calls belonging to any of these call sets, it won't be returned at all.
     * Currently, variants with no calls from any call set will never be returned.
     * </pre>
     */
    public java.lang.String getCallSetIds(int index) {
      return callSetIds_.get(index);
    }
    /**
     * <code>repeated string call_set_ids = 3;</code>
     *
     * <pre>
     * Only return variant calls which belong to call sets with these ids.
     * Leaving this blank returns all variant calls. If a variant has no
     * calls belonging to any of these call sets, it won't be returned at all.
     * Currently, variants with no calls from any call set will never be returned.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCallSetIdsBytes(int index) {
      return callSetIds_.getByteString(index);
    }
    /**
     * <code>repeated string call_set_ids = 3;</code>
     *
     * <pre>
     * Only return variant calls which belong to call sets with these ids.
     * Leaving this blank returns all variant calls. If a variant has no
     * calls belonging to any of these call sets, it won't be returned at all.
     * Currently, variants with no calls from any call set will never be returned.
     * </pre>
     */
    public Builder setCallSetIds(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCallSetIdsIsMutable();
      callSetIds_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string call_set_ids = 3;</code>
     *
     * <pre>
     * Only return variant calls which belong to call sets with these ids.
     * Leaving this blank returns all variant calls. If a variant has no
     * calls belonging to any of these call sets, it won't be returned at all.
     * Currently, variants with no calls from any call set will never be returned.
     * </pre>
     */
    public Builder addCallSetIds(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCallSetIdsIsMutable();
      callSetIds_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string call_set_ids = 3;</code>
     *
     * <pre>
     * Only return variant calls which belong to call sets with these ids.
     * Leaving this blank returns all variant calls. If a variant has no
     * calls belonging to any of these call sets, it won't be returned at all.
     * Currently, variants with no calls from any call set will never be returned.
     * </pre>
     */
    public Builder addAllCallSetIds(
        java.lang.Iterable<java.lang.String> values) {
      ensureCallSetIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, callSetIds_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string call_set_ids = 3;</code>
     *
     * <pre>
     * Only return variant calls which belong to call sets with these ids.
     * Leaving this blank returns all variant calls. If a variant has no
     * calls belonging to any of these call sets, it won't be returned at all.
     * Currently, variants with no calls from any call set will never be returned.
     * </pre>
     */
    public Builder clearCallSetIds() {
      callSetIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string call_set_ids = 3;</code>
     *
     * <pre>
     * Only return variant calls which belong to call sets with these ids.
     * Leaving this blank returns all variant calls. If a variant has no
     * calls belonging to any of these call sets, it won't be returned at all.
     * Currently, variants with no calls from any call set will never be returned.
     * </pre>
     */
    public Builder addCallSetIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCallSetIdsIsMutable();
      callSetIds_.add(value);
      onChanged();
      return this;
    }

    private java.lang.Object referenceName_ = "";
    /**
     * <code>optional string reference_name = 4;</code>
     *
     * <pre>
     * Required. Only return variants in this reference sequence.
     * </pre>
     */
    public java.lang.String getReferenceName() {
      java.lang.Object ref = referenceName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          referenceName_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string reference_name = 4;</code>
     *
     * <pre>
     * Required. Only return variants in this reference sequence.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getReferenceNameBytes() {
      java.lang.Object ref = referenceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        referenceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string reference_name = 4;</code>
     *
     * <pre>
     * Required. Only return variants in this reference sequence.
     * </pre>
     */
    public Builder setReferenceName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      referenceName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string reference_name = 4;</code>
     *
     * <pre>
     * Required. Only return variants in this reference sequence.
     * </pre>
     */
    public Builder clearReferenceName() {
      
      referenceName_ = getDefaultInstance().getReferenceName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string reference_name = 4;</code>
     *
     * <pre>
     * Required. Only return variants in this reference sequence.
     * </pre>
     */
    public Builder setReferenceNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      referenceName_ = value;
      onChanged();
      return this;
    }

    private long start_ ;
    /**
     * <code>optional int64 start = 5;</code>
     *
     * <pre>
     * The beginning of the window (0-based, inclusive) for which
     * overlapping variants should be returned. If unspecified, defaults to 0.
     * </pre>
     */
    public long getStart() {
      return start_;
    }
    /**
     * <code>optional int64 start = 5;</code>
     *
     * <pre>
     * The beginning of the window (0-based, inclusive) for which
     * overlapping variants should be returned. If unspecified, defaults to 0.
     * </pre>
     */
    public Builder setStart(long value) {
      
      start_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 start = 5;</code>
     *
     * <pre>
     * The beginning of the window (0-based, inclusive) for which
     * overlapping variants should be returned. If unspecified, defaults to 0.
     * </pre>
     */
    public Builder clearStart() {
      
      start_ = 0L;
      onChanged();
      return this;
    }

    private long end_ ;
    /**
     * <code>optional int64 end = 6;</code>
     *
     * <pre>
     * The end of the window, 0-based exclusive. If unspecified or 0, defaults to
     * the length of the reference.
     * </pre>
     */
    public long getEnd() {
      return end_;
    }
    /**
     * <code>optional int64 end = 6;</code>
     *
     * <pre>
     * The end of the window, 0-based exclusive. If unspecified or 0, defaults to
     * the length of the reference.
     * </pre>
     */
    public Builder setEnd(long value) {
      
      end_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 end = 6;</code>
     *
     * <pre>
     * The end of the window, 0-based exclusive. If unspecified or 0, defaults to
     * the length of the reference.
     * </pre>
     */
    public Builder clearEnd() {
      
      end_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object pageToken_ = "";
    /**
     * <code>optional string page_token = 7;</code>
     *
     * <pre>
     * The continuation token, which is used to page through large result sets.
     * To get the next page of results, set this parameter to the value of
     * `nextPageToken` from the previous response.
     * </pre>
     */
    public java.lang.String getPageToken() {
      java.lang.Object ref = pageToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pageToken_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string page_token = 7;</code>
     *
     * <pre>
     * The continuation token, which is used to page through large result sets.
     * To get the next page of results, set this parameter to the value of
     * `nextPageToken` from the previous response.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPageTokenBytes() {
      java.lang.Object ref = pageToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pageToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string page_token = 7;</code>
     *
     * <pre>
     * The continuation token, which is used to page through large result sets.
     * To get the next page of results, set this parameter to the value of
     * `nextPageToken` from the previous response.
     * </pre>
     */
    public Builder setPageToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pageToken_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string page_token = 7;</code>
     *
     * <pre>
     * The continuation token, which is used to page through large result sets.
     * To get the next page of results, set this parameter to the value of
     * `nextPageToken` from the previous response.
     * </pre>
     */
    public Builder clearPageToken() {
      
      pageToken_ = getDefaultInstance().getPageToken();
      onChanged();
      return this;
    }
    /**
     * <code>optional string page_token = 7;</code>
     *
     * <pre>
     * The continuation token, which is used to page through large result sets.
     * To get the next page of results, set this parameter to the value of
     * `nextPageToken` from the previous response.
     * </pre>
     */
    public Builder setPageTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pageToken_ = value;
      onChanged();
      return this;
    }

    private int pageSize_ ;
    /**
     * <code>optional int32 page_size = 8;</code>
     *
     * <pre>
     * The maximum number of variants to return. If unspecified, defaults to 5000.
     * </pre>
     */
    public int getPageSize() {
      return pageSize_;
    }
    /**
     * <code>optional int32 page_size = 8;</code>
     *
     * <pre>
     * The maximum number of variants to return. If unspecified, defaults to 5000.
     * </pre>
     */
    public Builder setPageSize(int value) {
      
      pageSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 page_size = 8;</code>
     *
     * <pre>
     * The maximum number of variants to return. If unspecified, defaults to 5000.
     * </pre>
     */
    public Builder clearPageSize() {
      
      pageSize_ = 0;
      onChanged();
      return this;
    }

    private int maxCalls_ ;
    /**
     * <code>optional int32 max_calls = 9;</code>
     *
     * <pre>
     * The maximum number of calls to return. However, at least one variant will
     * always be returned, even if it has more calls than this limit. If
     * unspecified, defaults to 5000.
     * </pre>
     */
    public int getMaxCalls() {
      return maxCalls_;
    }
    /**
     * <code>optional int32 max_calls = 9;</code>
     *
     * <pre>
     * The maximum number of calls to return. However, at least one variant will
     * always be returned, even if it has more calls than this limit. If
     * unspecified, defaults to 5000.
     * </pre>
     */
    public Builder setMaxCalls(int value) {
      
      maxCalls_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 max_calls = 9;</code>
     *
     * <pre>
     * The maximum number of calls to return. However, at least one variant will
     * always be returned, even if it has more calls than this limit. If
     * unspecified, defaults to 5000.
     * </pre>
     */
    public Builder clearMaxCalls() {
      
      maxCalls_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:google.genomics.v1.SearchVariantsRequest)
  }

  // @@protoc_insertion_point(class_scope:google.genomics.v1.SearchVariantsRequest)
  private static final com.google.genomics.v1.SearchVariantsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.genomics.v1.SearchVariantsRequest();
  }

  public static com.google.genomics.v1.SearchVariantsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  public static final com.google.protobuf.Parser<SearchVariantsRequest> PARSER =
      new com.google.protobuf.AbstractParser<SearchVariantsRequest>() {
    public SearchVariantsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new SearchVariantsRequest(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<SearchVariantsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SearchVariantsRequest> getParserForType() {
    return PARSER;
  }

  public com.google.genomics.v1.SearchVariantsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

