// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/genomics/v1/references.proto

package com.google.genomics.v1;

/**
 * Protobuf type {@code google.genomics.v1.SearchReferenceSetsRequest}
 */
public  final class SearchReferenceSetsRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:google.genomics.v1.SearchReferenceSetsRequest)
    SearchReferenceSetsRequestOrBuilder {
  // Use SearchReferenceSetsRequest.newBuilder() to construct.
  private SearchReferenceSetsRequest(com.google.protobuf.GeneratedMessage.Builder builder) {
    super(builder);
  }
  private SearchReferenceSetsRequest() {
    md5Checksums_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    accessions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    assemblyId_ = "";
    pageToken_ = "";
    pageSize_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private SearchReferenceSetsRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              md5Checksums_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            md5Checksums_.add(bs);
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              accessions_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            accessions_.add(bs);
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();

            assemblyId_ = bs;
            break;
          }
          case 34: {
            com.google.protobuf.ByteString bs = input.readBytes();

            pageToken_ = bs;
            break;
          }
          case 40: {

            pageSize_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        md5Checksums_ = md5Checksums_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        accessions_ = accessions_.getUnmodifiableView();
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.genomics.v1.ReferencesProto.internal_static_google_genomics_v1_SearchReferenceSetsRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.genomics.v1.ReferencesProto.internal_static_google_genomics_v1_SearchReferenceSetsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.genomics.v1.SearchReferenceSetsRequest.class, com.google.genomics.v1.SearchReferenceSetsRequest.Builder.class);
  }

  public static final com.google.protobuf.Parser<SearchReferenceSetsRequest> PARSER =
      new com.google.protobuf.AbstractParser<SearchReferenceSetsRequest>() {
    public SearchReferenceSetsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SearchReferenceSetsRequest(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<SearchReferenceSetsRequest> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int MD5CHECKSUMS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList md5Checksums_;
  /**
   * <code>repeated string md5checksums = 1;</code>
   *
   * <pre>
   * If present, return references for which the `md5checksum`
   * matches. See `ReferenceSet.md5checksum` for details.
   * </pre>
   */
  public com.google.protobuf.ProtocolStringList
      getMd5ChecksumsList() {
    return md5Checksums_;
  }
  /**
   * <code>repeated string md5checksums = 1;</code>
   *
   * <pre>
   * If present, return references for which the `md5checksum`
   * matches. See `ReferenceSet.md5checksum` for details.
   * </pre>
   */
  public int getMd5ChecksumsCount() {
    return md5Checksums_.size();
  }
  /**
   * <code>repeated string md5checksums = 1;</code>
   *
   * <pre>
   * If present, return references for which the `md5checksum`
   * matches. See `ReferenceSet.md5checksum` for details.
   * </pre>
   */
  public java.lang.String getMd5Checksums(int index) {
    return md5Checksums_.get(index);
  }
  /**
   * <code>repeated string md5checksums = 1;</code>
   *
   * <pre>
   * If present, return references for which the `md5checksum`
   * matches. See `ReferenceSet.md5checksum` for details.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getMd5ChecksumsBytes(int index) {
    return md5Checksums_.getByteString(index);
  }

  public static final int ACCESSIONS_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList accessions_;
  /**
   * <code>repeated string accessions = 2;</code>
   *
   * <pre>
   * If present, return references for which the accession matches any of these
   * strings. Best to give a version number, for example
   * `GCF_000001405.26`. If only the main accession number is given
   * then all records with that main accession will be returned, whichever
   * version. Note that different versions will have different sequences.
   * </pre>
   */
  public com.google.protobuf.ProtocolStringList
      getAccessionsList() {
    return accessions_;
  }
  /**
   * <code>repeated string accessions = 2;</code>
   *
   * <pre>
   * If present, return references for which the accession matches any of these
   * strings. Best to give a version number, for example
   * `GCF_000001405.26`. If only the main accession number is given
   * then all records with that main accession will be returned, whichever
   * version. Note that different versions will have different sequences.
   * </pre>
   */
  public int getAccessionsCount() {
    return accessions_.size();
  }
  /**
   * <code>repeated string accessions = 2;</code>
   *
   * <pre>
   * If present, return references for which the accession matches any of these
   * strings. Best to give a version number, for example
   * `GCF_000001405.26`. If only the main accession number is given
   * then all records with that main accession will be returned, whichever
   * version. Note that different versions will have different sequences.
   * </pre>
   */
  public java.lang.String getAccessions(int index) {
    return accessions_.get(index);
  }
  /**
   * <code>repeated string accessions = 2;</code>
   *
   * <pre>
   * If present, return references for which the accession matches any of these
   * strings. Best to give a version number, for example
   * `GCF_000001405.26`. If only the main accession number is given
   * then all records with that main accession will be returned, whichever
   * version. Note that different versions will have different sequences.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getAccessionsBytes(int index) {
    return accessions_.getByteString(index);
  }

  public static final int ASSEMBLY_ID_FIELD_NUMBER = 3;
  private java.lang.Object assemblyId_;
  /**
   * <code>optional string assembly_id = 3;</code>
   *
   * <pre>
   * If present, return reference sets for which a substring of their
   * `assemblyId` matches this string (case insensitive).
   * </pre>
   */
  public java.lang.String getAssemblyId() {
    java.lang.Object ref = assemblyId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        assemblyId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string assembly_id = 3;</code>
   *
   * <pre>
   * If present, return reference sets for which a substring of their
   * `assemblyId` matches this string (case insensitive).
   * </pre>
   */
  public com.google.protobuf.ByteString
      getAssemblyIdBytes() {
    java.lang.Object ref = assemblyId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      assemblyId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAGE_TOKEN_FIELD_NUMBER = 4;
  private java.lang.Object pageToken_;
  /**
   * <code>optional string page_token = 4;</code>
   *
   * <pre>
   * The continuation token, which is used to page through large result sets.
   * To get the next page of results, set this parameter to the value of
   * `nextPageToken` from the previous response.
   * </pre>
   */
  public java.lang.String getPageToken() {
    java.lang.Object ref = pageToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        pageToken_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string page_token = 4;</code>
   *
   * <pre>
   * The continuation token, which is used to page through large result sets.
   * To get the next page of results, set this parameter to the value of
   * `nextPageToken` from the previous response.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getPageTokenBytes() {
    java.lang.Object ref = pageToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pageToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAGE_SIZE_FIELD_NUMBER = 5;
  private int pageSize_;
  /**
   * <code>optional int32 page_size = 5;</code>
   *
   * <pre>
   * Specifies the maximum number of results to return in a single page.
   * </pre>
   */
  public int getPageSize() {
    return pageSize_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    for (int i = 0; i < md5Checksums_.size(); i++) {
      output.writeBytes(1, md5Checksums_.getByteString(i));
    }
    for (int i = 0; i < accessions_.size(); i++) {
      output.writeBytes(2, accessions_.getByteString(i));
    }
    if (!getAssemblyIdBytes().isEmpty()) {
      output.writeBytes(3, getAssemblyIdBytes());
    }
    if (!getPageTokenBytes().isEmpty()) {
      output.writeBytes(4, getPageTokenBytes());
    }
    if (pageSize_ != 0) {
      output.writeInt32(5, pageSize_);
    }
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < md5Checksums_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(md5Checksums_.getByteString(i));
      }
      size += dataSize;
      size += 1 * getMd5ChecksumsList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < accessions_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(accessions_.getByteString(i));
      }
      size += dataSize;
      size += 1 * getAccessionsList().size();
    }
    if (!getAssemblyIdBytes().isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, getAssemblyIdBytes());
    }
    if (!getPageTokenBytes().isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, getPageTokenBytes());
    }
    if (pageSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, pageSize_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static com.google.genomics.v1.SearchReferenceSetsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.genomics.v1.SearchReferenceSetsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.genomics.v1.SearchReferenceSetsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.genomics.v1.SearchReferenceSetsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.genomics.v1.SearchReferenceSetsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.google.genomics.v1.SearchReferenceSetsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.google.genomics.v1.SearchReferenceSetsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.google.genomics.v1.SearchReferenceSetsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.google.genomics.v1.SearchReferenceSetsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.google.genomics.v1.SearchReferenceSetsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return new Builder(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.google.genomics.v1.SearchReferenceSetsRequest prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code google.genomics.v1.SearchReferenceSetsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.genomics.v1.SearchReferenceSetsRequest)
      com.google.genomics.v1.SearchReferenceSetsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.genomics.v1.ReferencesProto.internal_static_google_genomics_v1_SearchReferenceSetsRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.genomics.v1.ReferencesProto.internal_static_google_genomics_v1_SearchReferenceSetsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.genomics.v1.SearchReferenceSetsRequest.class, com.google.genomics.v1.SearchReferenceSetsRequest.Builder.class);
    }

    // Construct using com.google.genomics.v1.SearchReferenceSetsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      md5Checksums_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      accessions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      assemblyId_ = "";

      pageToken_ = "";

      pageSize_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.genomics.v1.ReferencesProto.internal_static_google_genomics_v1_SearchReferenceSetsRequest_descriptor;
    }

    public com.google.genomics.v1.SearchReferenceSetsRequest getDefaultInstanceForType() {
      return com.google.genomics.v1.SearchReferenceSetsRequest.getDefaultInstance();
    }

    public com.google.genomics.v1.SearchReferenceSetsRequest build() {
      com.google.genomics.v1.SearchReferenceSetsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.google.genomics.v1.SearchReferenceSetsRequest buildPartial() {
      com.google.genomics.v1.SearchReferenceSetsRequest result = new com.google.genomics.v1.SearchReferenceSetsRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        md5Checksums_ = md5Checksums_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.md5Checksums_ = md5Checksums_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        accessions_ = accessions_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.accessions_ = accessions_;
      result.assemblyId_ = assemblyId_;
      result.pageToken_ = pageToken_;
      result.pageSize_ = pageSize_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.genomics.v1.SearchReferenceSetsRequest) {
        return mergeFrom((com.google.genomics.v1.SearchReferenceSetsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.genomics.v1.SearchReferenceSetsRequest other) {
      if (other == com.google.genomics.v1.SearchReferenceSetsRequest.getDefaultInstance()) return this;
      if (!other.md5Checksums_.isEmpty()) {
        if (md5Checksums_.isEmpty()) {
          md5Checksums_ = other.md5Checksums_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureMd5ChecksumsIsMutable();
          md5Checksums_.addAll(other.md5Checksums_);
        }
        onChanged();
      }
      if (!other.accessions_.isEmpty()) {
        if (accessions_.isEmpty()) {
          accessions_ = other.accessions_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureAccessionsIsMutable();
          accessions_.addAll(other.accessions_);
        }
        onChanged();
      }
      if (!other.getAssemblyId().isEmpty()) {
        assemblyId_ = other.assemblyId_;
        onChanged();
      }
      if (!other.getPageToken().isEmpty()) {
        pageToken_ = other.pageToken_;
        onChanged();
      }
      if (other.getPageSize() != 0) {
        setPageSize(other.getPageSize());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.genomics.v1.SearchReferenceSetsRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.genomics.v1.SearchReferenceSetsRequest) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList md5Checksums_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureMd5ChecksumsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        md5Checksums_ = new com.google.protobuf.LazyStringArrayList(md5Checksums_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string md5checksums = 1;</code>
     *
     * <pre>
     * If present, return references for which the `md5checksum`
     * matches. See `ReferenceSet.md5checksum` for details.
     * </pre>
     */
    public com.google.protobuf.ProtocolStringList
        getMd5ChecksumsList() {
      return md5Checksums_.getUnmodifiableView();
    }
    /**
     * <code>repeated string md5checksums = 1;</code>
     *
     * <pre>
     * If present, return references for which the `md5checksum`
     * matches. See `ReferenceSet.md5checksum` for details.
     * </pre>
     */
    public int getMd5ChecksumsCount() {
      return md5Checksums_.size();
    }
    /**
     * <code>repeated string md5checksums = 1;</code>
     *
     * <pre>
     * If present, return references for which the `md5checksum`
     * matches. See `ReferenceSet.md5checksum` for details.
     * </pre>
     */
    public java.lang.String getMd5Checksums(int index) {
      return md5Checksums_.get(index);
    }
    /**
     * <code>repeated string md5checksums = 1;</code>
     *
     * <pre>
     * If present, return references for which the `md5checksum`
     * matches. See `ReferenceSet.md5checksum` for details.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMd5ChecksumsBytes(int index) {
      return md5Checksums_.getByteString(index);
    }
    /**
     * <code>repeated string md5checksums = 1;</code>
     *
     * <pre>
     * If present, return references for which the `md5checksum`
     * matches. See `ReferenceSet.md5checksum` for details.
     * </pre>
     */
    public Builder setMd5Checksums(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureMd5ChecksumsIsMutable();
      md5Checksums_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string md5checksums = 1;</code>
     *
     * <pre>
     * If present, return references for which the `md5checksum`
     * matches. See `ReferenceSet.md5checksum` for details.
     * </pre>
     */
    public Builder addMd5Checksums(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureMd5ChecksumsIsMutable();
      md5Checksums_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string md5checksums = 1;</code>
     *
     * <pre>
     * If present, return references for which the `md5checksum`
     * matches. See `ReferenceSet.md5checksum` for details.
     * </pre>
     */
    public Builder addAllMd5Checksums(
        java.lang.Iterable<java.lang.String> values) {
      ensureMd5ChecksumsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, md5Checksums_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string md5checksums = 1;</code>
     *
     * <pre>
     * If present, return references for which the `md5checksum`
     * matches. See `ReferenceSet.md5checksum` for details.
     * </pre>
     */
    public Builder clearMd5Checksums() {
      md5Checksums_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string md5checksums = 1;</code>
     *
     * <pre>
     * If present, return references for which the `md5checksum`
     * matches. See `ReferenceSet.md5checksum` for details.
     * </pre>
     */
    public Builder addMd5ChecksumsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureMd5ChecksumsIsMutable();
      md5Checksums_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList accessions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureAccessionsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        accessions_ = new com.google.protobuf.LazyStringArrayList(accessions_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string accessions = 2;</code>
     *
     * <pre>
     * If present, return references for which the accession matches any of these
     * strings. Best to give a version number, for example
     * `GCF_000001405.26`. If only the main accession number is given
     * then all records with that main accession will be returned, whichever
     * version. Note that different versions will have different sequences.
     * </pre>
     */
    public com.google.protobuf.ProtocolStringList
        getAccessionsList() {
      return accessions_.getUnmodifiableView();
    }
    /**
     * <code>repeated string accessions = 2;</code>
     *
     * <pre>
     * If present, return references for which the accession matches any of these
     * strings. Best to give a version number, for example
     * `GCF_000001405.26`. If only the main accession number is given
     * then all records with that main accession will be returned, whichever
     * version. Note that different versions will have different sequences.
     * </pre>
     */
    public int getAccessionsCount() {
      return accessions_.size();
    }
    /**
     * <code>repeated string accessions = 2;</code>
     *
     * <pre>
     * If present, return references for which the accession matches any of these
     * strings. Best to give a version number, for example
     * `GCF_000001405.26`. If only the main accession number is given
     * then all records with that main accession will be returned, whichever
     * version. Note that different versions will have different sequences.
     * </pre>
     */
    public java.lang.String getAccessions(int index) {
      return accessions_.get(index);
    }
    /**
     * <code>repeated string accessions = 2;</code>
     *
     * <pre>
     * If present, return references for which the accession matches any of these
     * strings. Best to give a version number, for example
     * `GCF_000001405.26`. If only the main accession number is given
     * then all records with that main accession will be returned, whichever
     * version. Note that different versions will have different sequences.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAccessionsBytes(int index) {
      return accessions_.getByteString(index);
    }
    /**
     * <code>repeated string accessions = 2;</code>
     *
     * <pre>
     * If present, return references for which the accession matches any of these
     * strings. Best to give a version number, for example
     * `GCF_000001405.26`. If only the main accession number is given
     * then all records with that main accession will be returned, whichever
     * version. Note that different versions will have different sequences.
     * </pre>
     */
    public Builder setAccessions(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAccessionsIsMutable();
      accessions_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string accessions = 2;</code>
     *
     * <pre>
     * If present, return references for which the accession matches any of these
     * strings. Best to give a version number, for example
     * `GCF_000001405.26`. If only the main accession number is given
     * then all records with that main accession will be returned, whichever
     * version. Note that different versions will have different sequences.
     * </pre>
     */
    public Builder addAccessions(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAccessionsIsMutable();
      accessions_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string accessions = 2;</code>
     *
     * <pre>
     * If present, return references for which the accession matches any of these
     * strings. Best to give a version number, for example
     * `GCF_000001405.26`. If only the main accession number is given
     * then all records with that main accession will be returned, whichever
     * version. Note that different versions will have different sequences.
     * </pre>
     */
    public Builder addAllAccessions(
        java.lang.Iterable<java.lang.String> values) {
      ensureAccessionsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, accessions_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string accessions = 2;</code>
     *
     * <pre>
     * If present, return references for which the accession matches any of these
     * strings. Best to give a version number, for example
     * `GCF_000001405.26`. If only the main accession number is given
     * then all records with that main accession will be returned, whichever
     * version. Note that different versions will have different sequences.
     * </pre>
     */
    public Builder clearAccessions() {
      accessions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string accessions = 2;</code>
     *
     * <pre>
     * If present, return references for which the accession matches any of these
     * strings. Best to give a version number, for example
     * `GCF_000001405.26`. If only the main accession number is given
     * then all records with that main accession will be returned, whichever
     * version. Note that different versions will have different sequences.
     * </pre>
     */
    public Builder addAccessionsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAccessionsIsMutable();
      accessions_.add(value);
      onChanged();
      return this;
    }

    private java.lang.Object assemblyId_ = "";
    /**
     * <code>optional string assembly_id = 3;</code>
     *
     * <pre>
     * If present, return reference sets for which a substring of their
     * `assemblyId` matches this string (case insensitive).
     * </pre>
     */
    public java.lang.String getAssemblyId() {
      java.lang.Object ref = assemblyId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          assemblyId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string assembly_id = 3;</code>
     *
     * <pre>
     * If present, return reference sets for which a substring of their
     * `assemblyId` matches this string (case insensitive).
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAssemblyIdBytes() {
      java.lang.Object ref = assemblyId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        assemblyId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string assembly_id = 3;</code>
     *
     * <pre>
     * If present, return reference sets for which a substring of their
     * `assemblyId` matches this string (case insensitive).
     * </pre>
     */
    public Builder setAssemblyId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      assemblyId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string assembly_id = 3;</code>
     *
     * <pre>
     * If present, return reference sets for which a substring of their
     * `assemblyId` matches this string (case insensitive).
     * </pre>
     */
    public Builder clearAssemblyId() {
      
      assemblyId_ = getDefaultInstance().getAssemblyId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string assembly_id = 3;</code>
     *
     * <pre>
     * If present, return reference sets for which a substring of their
     * `assemblyId` matches this string (case insensitive).
     * </pre>
     */
    public Builder setAssemblyIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      assemblyId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object pageToken_ = "";
    /**
     * <code>optional string page_token = 4;</code>
     *
     * <pre>
     * The continuation token, which is used to page through large result sets.
     * To get the next page of results, set this parameter to the value of
     * `nextPageToken` from the previous response.
     * </pre>
     */
    public java.lang.String getPageToken() {
      java.lang.Object ref = pageToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pageToken_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string page_token = 4;</code>
     *
     * <pre>
     * The continuation token, which is used to page through large result sets.
     * To get the next page of results, set this parameter to the value of
     * `nextPageToken` from the previous response.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPageTokenBytes() {
      java.lang.Object ref = pageToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pageToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string page_token = 4;</code>
     *
     * <pre>
     * The continuation token, which is used to page through large result sets.
     * To get the next page of results, set this parameter to the value of
     * `nextPageToken` from the previous response.
     * </pre>
     */
    public Builder setPageToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pageToken_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string page_token = 4;</code>
     *
     * <pre>
     * The continuation token, which is used to page through large result sets.
     * To get the next page of results, set this parameter to the value of
     * `nextPageToken` from the previous response.
     * </pre>
     */
    public Builder clearPageToken() {
      
      pageToken_ = getDefaultInstance().getPageToken();
      onChanged();
      return this;
    }
    /**
     * <code>optional string page_token = 4;</code>
     *
     * <pre>
     * The continuation token, which is used to page through large result sets.
     * To get the next page of results, set this parameter to the value of
     * `nextPageToken` from the previous response.
     * </pre>
     */
    public Builder setPageTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pageToken_ = value;
      onChanged();
      return this;
    }

    private int pageSize_ ;
    /**
     * <code>optional int32 page_size = 5;</code>
     *
     * <pre>
     * Specifies the maximum number of results to return in a single page.
     * </pre>
     */
    public int getPageSize() {
      return pageSize_;
    }
    /**
     * <code>optional int32 page_size = 5;</code>
     *
     * <pre>
     * Specifies the maximum number of results to return in a single page.
     * </pre>
     */
    public Builder setPageSize(int value) {
      
      pageSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 page_size = 5;</code>
     *
     * <pre>
     * Specifies the maximum number of results to return in a single page.
     * </pre>
     */
    public Builder clearPageSize() {
      
      pageSize_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:google.genomics.v1.SearchReferenceSetsRequest)
  }

  // @@protoc_insertion_point(class_scope:google.genomics.v1.SearchReferenceSetsRequest)
  private static final com.google.genomics.v1.SearchReferenceSetsRequest defaultInstance;static {
    defaultInstance = new com.google.genomics.v1.SearchReferenceSetsRequest();
  }

  public static com.google.genomics.v1.SearchReferenceSetsRequest getDefaultInstance() {
    return defaultInstance;
  }

  public com.google.genomics.v1.SearchReferenceSetsRequest getDefaultInstanceForType() {
    return defaultInstance;
  }

}

