// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/genomics/v1/variants.proto

package com.google.genomics.v1;

public interface SearchVariantsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.genomics.v1.SearchVariantsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string variant_set_ids = 1;</code>
   *
   * <pre>
   * At most one variant set ID must be provided. Only variants from this
   * variant set will be returned. If omitted, a call set id must be included in
   * the request.
   * </pre>
   */
  com.google.protobuf.ProtocolStringList
      getVariantSetIdsList();
  /**
   * <code>repeated string variant_set_ids = 1;</code>
   *
   * <pre>
   * At most one variant set ID must be provided. Only variants from this
   * variant set will be returned. If omitted, a call set id must be included in
   * the request.
   * </pre>
   */
  int getVariantSetIdsCount();
  /**
   * <code>repeated string variant_set_ids = 1;</code>
   *
   * <pre>
   * At most one variant set ID must be provided. Only variants from this
   * variant set will be returned. If omitted, a call set id must be included in
   * the request.
   * </pre>
   */
  java.lang.String getVariantSetIds(int index);
  /**
   * <code>repeated string variant_set_ids = 1;</code>
   *
   * <pre>
   * At most one variant set ID must be provided. Only variants from this
   * variant set will be returned. If omitted, a call set id must be included in
   * the request.
   * </pre>
   */
  com.google.protobuf.ByteString
      getVariantSetIdsBytes(int index);

  /**
   * <code>optional string variant_name = 2;</code>
   *
   * <pre>
   * Only return variants which have exactly this name.
   * </pre>
   */
  java.lang.String getVariantName();
  /**
   * <code>optional string variant_name = 2;</code>
   *
   * <pre>
   * Only return variants which have exactly this name.
   * </pre>
   */
  com.google.protobuf.ByteString
      getVariantNameBytes();

  /**
   * <code>repeated string call_set_ids = 3;</code>
   *
   * <pre>
   * Only return variant calls which belong to call sets with these ids.
   * Leaving this blank returns all variant calls. If a variant has no
   * calls belonging to any of these call sets, it won't be returned at all.
   * Currently, variants with no calls from any call set will never be returned.
   * </pre>
   */
  com.google.protobuf.ProtocolStringList
      getCallSetIdsList();
  /**
   * <code>repeated string call_set_ids = 3;</code>
   *
   * <pre>
   * Only return variant calls which belong to call sets with these ids.
   * Leaving this blank returns all variant calls. If a variant has no
   * calls belonging to any of these call sets, it won't be returned at all.
   * Currently, variants with no calls from any call set will never be returned.
   * </pre>
   */
  int getCallSetIdsCount();
  /**
   * <code>repeated string call_set_ids = 3;</code>
   *
   * <pre>
   * Only return variant calls which belong to call sets with these ids.
   * Leaving this blank returns all variant calls. If a variant has no
   * calls belonging to any of these call sets, it won't be returned at all.
   * Currently, variants with no calls from any call set will never be returned.
   * </pre>
   */
  java.lang.String getCallSetIds(int index);
  /**
   * <code>repeated string call_set_ids = 3;</code>
   *
   * <pre>
   * Only return variant calls which belong to call sets with these ids.
   * Leaving this blank returns all variant calls. If a variant has no
   * calls belonging to any of these call sets, it won't be returned at all.
   * Currently, variants with no calls from any call set will never be returned.
   * </pre>
   */
  com.google.protobuf.ByteString
      getCallSetIdsBytes(int index);

  /**
   * <code>optional string reference_name = 4;</code>
   *
   * <pre>
   * Required. Only return variants in this reference sequence.
   * </pre>
   */
  java.lang.String getReferenceName();
  /**
   * <code>optional string reference_name = 4;</code>
   *
   * <pre>
   * Required. Only return variants in this reference sequence.
   * </pre>
   */
  com.google.protobuf.ByteString
      getReferenceNameBytes();

  /**
   * <code>optional int64 start = 5;</code>
   *
   * <pre>
   * The beginning of the window (0-based, inclusive) for which
   * overlapping variants should be returned. If unspecified, defaults to 0.
   * </pre>
   */
  long getStart();

  /**
   * <code>optional int64 end = 6;</code>
   *
   * <pre>
   * The end of the window, 0-based exclusive. If unspecified or 0, defaults to
   * the length of the reference.
   * </pre>
   */
  long getEnd();

  /**
   * <code>optional string page_token = 7;</code>
   *
   * <pre>
   * The continuation token, which is used to page through large result sets.
   * To get the next page of results, set this parameter to the value of
   * `nextPageToken` from the previous response.
   * </pre>
   */
  java.lang.String getPageToken();
  /**
   * <code>optional string page_token = 7;</code>
   *
   * <pre>
   * The continuation token, which is used to page through large result sets.
   * To get the next page of results, set this parameter to the value of
   * `nextPageToken` from the previous response.
   * </pre>
   */
  com.google.protobuf.ByteString
      getPageTokenBytes();

  /**
   * <code>optional int32 page_size = 8;</code>
   *
   * <pre>
   * The maximum number of variants to return. If unspecified, defaults to 5000.
   * </pre>
   */
  int getPageSize();

  /**
   * <code>optional int32 max_calls = 9;</code>
   *
   * <pre>
   * The maximum number of calls to return. However, at least one variant will
   * always be returned, even if it has more calls than this limit. If
   * unspecified, defaults to 5000.
   * </pre>
   */
  int getMaxCalls();
}
