// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/genomics/v1/variants.proto

package com.google.genomics.v1;

public interface VariantSetMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.genomics.v1.VariantSetMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string key = 1;</code>
   *
   * <pre>
   * The top-level key.
   * </pre>
   */
  java.lang.String getKey();
  /**
   * <code>optional string key = 1;</code>
   *
   * <pre>
   * The top-level key.
   * </pre>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>optional string value = 2;</code>
   *
   * <pre>
   * The value field for simple metadata
   * </pre>
   */
  java.lang.String getValue();
  /**
   * <code>optional string value = 2;</code>
   *
   * <pre>
   * The value field for simple metadata
   * </pre>
   */
  com.google.protobuf.ByteString
      getValueBytes();

  /**
   * <code>optional string id = 4;</code>
   *
   * <pre>
   * User-provided ID field, not enforced by this API.
   * Two or more pieces of structured metadata with identical
   * id and key fields are considered equivalent.
   * </pre>
   */
  java.lang.String getId();
  /**
   * <code>optional string id = 4;</code>
   *
   * <pre>
   * User-provided ID field, not enforced by this API.
   * Two or more pieces of structured metadata with identical
   * id and key fields are considered equivalent.
   * </pre>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>optional .google.genomics.v1.VariantSetMetadata.Type type = 5;</code>
   *
   * <pre>
   * The type of data. Possible types include: Integer, Float,
   * Flag, Character, and String.
   * </pre>
   */
  int getTypeValue();
  /**
   * <code>optional .google.genomics.v1.VariantSetMetadata.Type type = 5;</code>
   *
   * <pre>
   * The type of data. Possible types include: Integer, Float,
   * Flag, Character, and String.
   * </pre>
   */
  com.google.genomics.v1.VariantSetMetadata.Type getType();

  /**
   * <code>optional int32 number = 6;</code>
   *
   * <pre>
   * The number of values that can be included in a field described by this
   * metadata.
   * </pre>
   */
  int getNumber();

  /**
   * <code>optional string description = 7;</code>
   *
   * <pre>
   * A textual description of this metadata.
   * </pre>
   */
  java.lang.String getDescription();
  /**
   * <code>optional string description = 7;</code>
   *
   * <pre>
   * A textual description of this metadata.
   * </pre>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>map&lt;string, .google.protobuf.ListValue&gt; info = 3;</code>
   *
   * <pre>
   * Remaining structured metadata key-value pairs. This must be of the form
   * map&lt;string, string[]&gt; (string key mapping to a list of string values).
   * </pre>
   */
  java.util.Map<java.lang.String, com.google.protobuf.ListValue>
  getInfo();
}
